### ISSUE TITLE
"DISCORD_TOKEN" is required to run the bot

### ISSUE THREAD

**Issue by as1ra** [abdulrahman1s/Akinator-Bot#4]
btw I already put the discord token in the .env file I've basically tried everything but it would not work if you know how to fix this please reply to this thank you

**Comment by as1ra** [comment]
Please Reply to this if you know how to Fix this.

**Comment by as1ra** [comment]
abdulrahman1s if youre seeing this please reply to this

**Comment by abdulrahman1s** [comment]
Make sure to rename `.env.example` to `.env`
And if you running the bot on replit just put it in environment variables.

**Comment by abdulrahman1s** [comment]
If everything won't work..
Just put your token directly in `index.js` by inserting this line on top:

```
process.env.DISCORD_TOKEN = "your-token"

```

**Comment by as1ra** [comment]
![Screenshot 2022-05-07 173340](https://user-images.githubusercontent.com/105108603/167258774-dd8fbdbe-cc7d-43ce-bdc0-2c5f470772b9.png)
for some reason it doesn't work I don't know how it doesn't work I'm not an expert at this.

**Comment by abdulrahman1s** [comment]
> If everything won't work.. Just put your token directly in `index.js` by inserting this line on top:
> 
> ```js
> process.env.DISCORD_TOKEN = "your-token"
> ```

did you try this solution?

**Comment by as1ra** [comment]
yes I've tried it and it still doesn't work

**Comment by as1ra** [comment]
also sorry for late reply I was sleeping lol

**Comment by abdulrahman1s** [comment]
did you inserted the line on TOP?

**Comment by as1ra** [comment]
yes
