### ISSUE TITLE
this is addressed to the creator of the bot


### ISSUE THREAD

**Issue by Polin2711** [abdulrahman1s/Akinator-Bot#6]
Dou you want to do a games bot with me??
Mi discord: Polin#2895

**Comment by abdulrahman1s** [comment]
I'm not that interested in bots these days
I currently working on my own chat platform (yes, am crazy to build my own discord lol)
But sometimes I do freelance to live,
If you looking for a freelancer to build an idea I could be that one :)

**Comment by Polin2711** [comment]
You could contact me on my discord when you are interested, please.

**Comment by Polin2711** [comment]
You could contact me on my discord when you are interested, please.
